### PR TITLE
Test more

### PR DESCRIPTION
**Pull request by rocky**
Changes to allow this to be distributed on CPAN adding Perl-style tests. Add Travis CI testing.

About the merge conflict. This does include the change snp-coding updated from around Dec 17 or so. But because the location of biopop has moved to bin (needed for distribution) git merge won't pick this up automatically.

### CODE REVIEW

**Comment by yzhernand** [comment]
Hi rocky,

First off, thanks for these, especially the effort to make these CPAN distributable. Second, sorry for the delay in reviewing these patches. I'm reviewing these right now, and I'll merge them if it all looks good.

**Comment by rocky** [comment]
np. You guys are busy. I get that.

**Comment by yzhernand** [comment]
Merge complete. Thanks for these! Sorry for the huge delay!

**Comment by rocky** [comment]
no problem. Onward and upward!

**Comment by yzhernand** [comment]
The rlib package needs to be installed. I'm installing it on the lab
machines now.

**Pull request merged**
